version: "3"

services:
  iron_x:
    container_name: iron_x
    build:
      context: .
      shm_size: 25G
    volumes:
      - .:/app
    command: bash -c "jupyter lab --ip=0.0.0.0 --port=8788 --no-browser --allow-root --NotebookApp.token='rndbox' && tensorboard --logdir=runs"
    ports:
      - 8788:8788
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  tensorboard:
    container_name: tensorboard_iron_x
    build: .
    volumes:
      - .:/app
    ports:
      - 8789:8789
    command: tensorboard --logdir=/app/runs --host 0.0.0.0 --port 8788
